#!/bin/sh
set -eu

P=1
N=$((3 * 1000 * 1000))

echo "N = ${N}"
echo "P = ${P}"

mvn package >&2
time spark-submit --class com.cloudera.datascience.montecarlorisk.MonteCarloRisk --master "local[${P}]" \
  target/montecarlo-risk-0.0.1-SNAPSHOT.jar \
  data/instruments.csv ${N} ${P} data/means.csv data/covariances.csv

